
version: "3.4"

services:
  postgres:
    volumes:
      - db_data_dev:/var/lib/postgresql/data
  app:
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - ./:/app
    healthcheck:
      test: /bin/true
  redis:
    ports:
      - "${BROKER_PORT:-6379}:${BROKER_PORT:-6379}"
  nginx:
    command: /bin/true
    restart: "no"

volumes:
  db_data_dev:
    driver: local