
version: "3.4"

services:
  postgres:
    volumes:
      - db_data_dev:/var/lib/postgresql/data
  app:
    image: pkwarc/stocker-app:latest
    build:
      context: .
      args:
        - POETRY_VERSION=${POETRY_VERSION}
    expose:
      - "${APP_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - TARGET_ENV=${TARGET_ENV}
      - APP_PORT=${APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    command: runserver
    depends_on:
      - "postgres"
      - "rabbitmq"
  celery:
    command: /bin/true
  nginx:
    command: /bin/true

volumes:
  db_data_dev:
    driver: local