
version: "3.4"

services:
  postgres:
    volumes:
      - db_data_dev:/var/lib/postgresql/data
  app:
    image: pkwarc/stocker-app:latest
    build:
      target: development
      dockerfile: python_docker/Dockerfile
      context: .
      args:
        - POETRY_VERSION=${POETRY_VERSION:-1.1.10}
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - ./:/app
  redis:
    ports:
      - "${BROKER_PORT:-6379}:${BROKER_PORT:-6379}"
  nginx:
    command: /bin/true
    restart: "no"

volumes:
  db_data_dev:
    driver: local