# Generated by Django 3.2.7 on 2021-10-10 12:22
import datetime
from django.db import migrations


def populate_exchange(apps, schema_editor):
    Exchange = apps.get_model('notifications', 'Exchange')
    Exchange.objects.create(
        mic='XNAS',
        name='NASDAQ',
        description='No description',
        opens_at=datetime.time(hour=14, minute=30),
        closes_at=datetime.time(hour=21, minute=00)
    )


def populate_currency(apps, schema_editor):
    Currency = apps.get_model('notifications', 'Currency')
    Currency.objects.create(
        symbol='USD'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20211010_1216'),
    ]

    operations = [
        migrations.RunPython(populate_exchange),
        migrations.RunPython(populate_currency)
    ]
