name: Build docker images
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.STOCKER_DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.STOCKER_DOCKER_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images and run the app
        run: docker-compose --env-file ./.github/.env.github up -d
      - name: Stop and remove containers
        run: docker-compose --env-file ./.github/.env.github down --volumes
      - name: Run tests
        run: docker-compose --env-file ./.github/.env.github run app test
      - name: Setup docker
        run: docker login --username=$DOCKER_USER --password=$DOCKER_PASS
      - name: Push images to the dockerhub
        run: docker-compose --env-file ./.github/.env.github push