name: GitHub Actions Demo
on:
  push:
    branches:
      - test/github-actions
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and run docker images
        run: docker-compose --env-file ./.github/.env.github up -d
      - name: Run pytest
        run: docker-compose exec app pytest