name: GitHub Actions Demo
on:
  push:
    branches:
      - test/github-actions
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose build
      - name: Run the containers
        run: docker-compose up -d
